# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d06d2e2e09f9e9a4da3a6b917c27a823188c1f8a27502c1dcb15075f45c7d519feb047bad83d836d720008f2039d73ed2ee29484ab6a61ee161bcdd27b4ee1e5

test:
  secret_key_base: 0e7d2e4d1bddec57b287af436055f45e99c070688858882cdc10f82cccef9e72ac196ab67b7ee7cef2e2c9fcd2302d320ae7bc25f6837e9221b7fc677d648559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
